(ns alex-comma-game.game
  )

(def category '(:id :name))
(def categories
  (list
   (zipmap category '(1 "A comma is used to set off a word that introduces a sentence such as yes, no, and well."))
   (zipmap category '(2 "A comma belongs before the conjunction and, or, or but in a compound sentence."))
   (zipmap category '(3 "Use commas to separate three or more words in a series.  Do not use a comma after the last word in the series."))
   (zipmap category '(4 "Use commas to separate three or more phrases in a series.  Do not use a comma after the last phrase in the sentence."))
   (zipmap category '(5 "Use a comma after a greeting and after the closing of a friendly letter."))
   (zipmap category '(6 "A comma sets off a person's name when the person is being directly spoken to."))
   (zipmap category '(7 "Use a comma between the day and the year in a date.  Do not use a comma if only the month and year are given."))
   (zipmap category '(8 "Use a comma between the names of a city and a state."))
   (zipmap category '(9 "Use a comma to set off a direct quotation."))
   (zipmap category '(10 "Appositive Brushstroke"))
   (zipmap category '(11 "Adjectives Out of Order Brushstroke"))
   (zipmap category '(12 "Participle Brushstroke"))
   )
  )

(def sentence '(:text :answer))
(def sentences
  (list
   (zipmap sentence '("Yes, my teacher is Mrs. McLaughlin." 1))
   (zipmap sentence '("Well, I think tomorrow I will feel better." 1))
   (zipmap sentence '("No, I'm 10." 1))
   (zipmap sentence '("I walked to the store, and I bought all the groceries." 2))
   (zipmap sentence '("I have my bike, but I don't ride it much." 2))
   (zipmap sentence '("May I ride my bike, or do I have to ride with you?" 2))
   (zipmap sentence '("I once played soccer, basketball, and football." 3))
   (zipmap sentence '("I went to a restaurant and ordered chicken, cookies, and chips and dip." 3))
   (zipmap sentence '("My favorite candies are Snickers, Twix, and M&Ms." 3))
   (zipmap sentence '("When I got home I changed by clothes, washed my hands, and fed my dogs." 4))
   (zipmap sentence '("I make popcorn by putting kernels in a paper bag, microwaving it, and pouring butter on top." 4))
   (zipmap sentence '("Dear Stacy,<br/>I hope you have a great birthday.  40 is not old.<br/>Your friend,<br/>Alexandra" 5))
   (zipmap sentence '("Bob, you need to clean your room." 6))
   (zipmap sentence '("Mrs. McLaughlin, do you teach fifth grade?" 6))
   (zipmap sentence '("Tanner, I have a surprise for you." 6))
   (zipmap sentence '("August 26, 2013" 7))
   (zipmap sentence '("December 25, 2013" 7))
   (zipmap sentence '("August 6, 2013" 7))
   (zipmap sentence '("February 11, 2013" 7))
   (zipmap sentence '("Flower Mound, TX" 8))
   (zipmap sentence '("Oklahoma City, OK" 8))
   (zipmap sentence '("Houston, TX" 8))
   (zipmap sentence '("Norman, OK" 8))
   (zipmap sentence '("Mrs. McLaughlin said, \"Stop Talking.\"" 9))
   (zipmap sentence '("Mom said, \"It's dinner time.\"" 9))
   (zipmap sentence '("I said, \"What are we having for dinner?\"" 9))
   (zipmap sentence '("The car, a 1936 Ford, went into the parking lot." 10))
   (zipmap sentence '("Matt, the Varsity quarterback, couldn’t solve two plus two." 10))
   (zipmap sentence '("Mr. G, the student teacher, is working with us for a few months." 10))
   (zipmap sentence '("The school building, old and leaky, was in desperate need of repair." 11))
   (zipmap sentence '("Ponyboy, young and daring, is the narrator of The Outsiders." 11))
   (zipmap sentence '("The speedy car, red and shiny, screeched around the corner." 11))
   (zipmap sentence '("Bouncing, clanking, rattling, the car went into the parking lot." 12))
   (zipmap sentence '("Skidding across the floor, the late student zoomed into class." 12))
   (zipmap sentence '("The late student zoomed into class, skidding across the floor." 12))
   )
  )
